# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.TextField(max_length=200)),
                ('address_line_2', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('scope', models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')])),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.SmallIntegerField(choices=[(0, 'undergraduate'), (1, 'postgraduate'), (2, 'doctoral'), (3, 'dual_degree')], null=True)),
                ('institute_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('convocation_year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'others')])),
                ('blood_group', models.SmallIntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'AB'), (3, 'O')])),
                ('marital_status', models.SmallIntegerField(choices=[(0, 'married'), (1, 'single')])),
                ('photograph', models.ImageField(upload_to='images')),
                ('nationality', models.CharField(max_length=50)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(max_length=254, null=True)),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(max_length=20)),
                ('link_facebook', models.CharField(max_length=100)),
                ('link_twitter', models.CharField(max_length=100)),
                ('link_linkedin', models.CharField(max_length=100)),
                ('link_skype', models.CharField(max_length=100)),
                ('choice_facebook_scope', models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')])),
                ('choice_twitter_scope', models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')])),
                ('choice_linkedin_scope', models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')])),
                ('choice_skype_scope', models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')])),
                ('link_github', models.CharField(max_length=100)),
                ('link_blog', models.CharField(max_length=200)),
                ('link_website', models.CharField(max_length=200)),
                ('current_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_address', to='portal.Address')),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='portal.Address')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=150)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('sector', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('founder', models.BooleanField(default=False)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.User')),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.User'),
        ),
    ]
