# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_address', to='portal.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='portal.Address'),
        ),
    ]
