# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170804_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
