# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170804_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choice_facebook_scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_linkedin_scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_skype_scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_twitter_scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_blog',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_github',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_skype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(0, 'married'), (1, 'single')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photograph',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
