# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170804_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], default=portal.models.Visibility(2)),
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_facebook_scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], default=portal.models.Visibility(2), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_linkedin_scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], default=portal.models.Visibility(2), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_skype_scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], default=portal.models.Visibility(2), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_twitter_scope',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'only_me'), (2, 'iiita')], default=portal.models.Visibility(2), null=True),
        ),
    ]
