# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('portal', '0004_auto_20170805_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.User.handle_upload),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.User'),
        ),
    ]
