# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170804_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'AB'), (3, 'O')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_blog',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_skype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'married'), (1, 'single')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
