# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20170804_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_1',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
