# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='session',
        ),
        migrations.AddField(
            model_name='usersession',
            name='sessionid',
            field=models.TextField(default='ace6375eeab941238123abe170a6b18d', max_length=100, primary_key=True, serialize=False),
        ),
    ]
