# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20170805_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'married'), (1, 'single'), (2, 'divorced')], null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='sessionid',
            field=models.TextField(default='7107e63dc087497686b47c8c0aaf3958', max_length=100, primary_key=True, serialize=False),
        ),
    ]
